### ISSUE TITLE
data augmantations

### ISSUE THREAD

**Issue by cissoidx** [Alibaba-MIIL/ImageNet21K#43]
Hello, I see that you already have randaugment in you data preprocessing. Why do you in additional have cutoutPIL in transform knowing that randaugment has cutout? Does it have better performance?

**Comment by mrT23** [comment]
this is not unique to ImageNet21K training. large cutout helps, a lot, both for upstream and downstream tasks..  it's probably the most important augmentation there is.
you need much more than what is provided by randAugment package (and to my best memory, in their article they manually added an additional cutout).

as an examle, all the default training in [timm ](https://github.com/rwightman/pytorch-image-models/blob/master/train.py)  use additional cutout ('reprob')
https://rwightman.github.io/pytorch-image-models/training_hparam_examples/

cutoutPIL is a specific implementation of mine, that is more efficient than common implementations, since it works on uint8 images, not float32
