### ISSUE TITLE
could I transferred the paper's idea to object detection task?

### ISSUE THREAD

**Issue by cs-heibao** [Alibaba-MIIL/ImageNet21K#44]
Recently, do an object fine-grained detection task, is it convenient to transferred to object detection?
thanks

**Comment by mrT23** [comment]
in the revised version of the paper, i share results on ms-coco detection task, with MTResNet backbone, where switching pretraining from 1K to 21K improved results.

some people said in the git that with resnet50 they were not able to get an improvement. 
i dont know, i suspect they might had a bug in loading the weights.,
since resnet50  is a crappy network anyway, my recommendation is not to use it, and switch to mtresnet (or MBV3).
the original 1K weights can be found at:
https://github.com/Alibaba-MIIL/TResNet/blob/master/MODEL_ZOO.md
